Практическая работа Анализ и обработка данных с Pandas и NumPy

In [429]:
import pandas as pd 
import numpy as np

In [430]:
df = pd.read_csv("train (1).csv")
n = int(input())
df.head(n)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [431]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [432]:
col, rows = df.shape
print(col, rows)

891 12

In [433]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [434]:
print(df.columns.dtype)

str

In [435]:
categorial_features = df.select_dtypes(include='object')
numeric_features = df.select_dtypes(include='number')
print(categorial_features)
print(numeric_features)

                                                  Name     Sex  \
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

               Ticket Cabin Embarked
0           A/5 21171   NaN        S
1            PC 17599   C85        C
2    STON/O2. 3101282   NaN        S
3              113803  C123        S
4              373450   NaN        S
..                ...   ...      ...
886            211536   NaN        S
887            112053   B42        S
888        W./C. 6607   NaN        S
889            111369  C148        C
890            370376   NaN        Q

[891 rows x 5 columns]
     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

/var/folders/ct/z9q0g5h57n54lw5pf0l77g8h0000gn/T/ipykernel_22198/1683590874.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/dev/user_guide/migration.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorial_features = df.select_dtypes(include='object')

In [436]:
# numeric_features.mean()
# numeric_features.median()
# numeric_features.min()
# numeric_features.max()
# numeric_features.std()
numeric_features.agg(["mean", "median", "min", "max", "std"])

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
median,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429

In [437]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [438]:
df["Embarked"].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [439]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [440]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.771044
Embarked       0.002245
dtype: float64

In [441]:
df.columns[np.argmax(df.isna().mean())]

'Cabin'

In [442]:
stat_age = df["Age"].agg(["mean", "median", "min", "max", "std", "count"])
stat_age

mean       29.699118
median     28.000000
min         0.420000
max        80.000000
std        14.526497
count     714.000000
Name: Age, dtype: float64

In [443]:
age_median = stat_age["median"]
df["Age"] = df["Age"].fillna(age_median)

In [444]:
print(df["Age"].tail())
stat_age_filled = df["Age"].agg(["mean", "median", "min", "max", "std", "count"])
stat_age_filled

886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, dtype: float64

mean       29.361582
median     28.000000
min         0.420000
max        80.000000
std        13.019697
count     891.000000
Name: Age, dtype: float64

In [445]:
comprasion_age = pd.DataFrame({
    "До обработки" : stat_age,
    "После обработки" : stat_age_filled
})
comprasion_age

        До обработки  После обработки
mean       29.699118        29.361582
median     28.000000        28.000000
min         0.420000         0.420000
max        80.000000        80.000000
std        14.526497        13.019697
count     714.000000       891.000000

In [446]:
df = df.dropna(subset=["Embarked"])
df["Embarked"].isna().sum()

np.int64(0)

In [447]:
if df["Cabin"].isna().mean() * 100 > 50: df = df.drop(columns="Cabin")
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='str')

In [448]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [449]:
print({"До обработки" : (col, rows), "После обработки" : df.shape})

{'До обработки': (891, 12), 'После обработки': (889, 11)}

In [450]:
np.mean(df["Survived"])

np.float64(0.38245219347581555)

In [451]:
man_surv = np.mean(df["Survived"].where(df["Sex"] == "male"))
woman_surv = np.mean(df["Survived"].where(df["Sex"] == "female"))
print("Выживаемость мужчин: ", man_surv, '\n', "Выживаемость женщин: ", woman_surv)

Выживаемость мужчин:  0.18890814558058924
 Выживаемость женщин:  0.7403846153846154

In [452]:
data = [
    [np.mean(df["Age"].where((df["Sex"] == "male") & (df["Survived"] == 1))),
    np.mean(df["Age"].where((df["Sex"] == "male") & (df["Survived"] == 0)))],
    [np.mean(df["Age"].where((df["Sex"] == "female") & (df["Survived"] == 1))),
    np.mean(df["Age"].where((df["Sex"] == "female") & (df["Survived"] == 0)))]
]
print("Срдений возраст выживших/погибших")
pd.DataFrame(
    data, 
    columns=[ "Выжили", "Погибли" ],
    index=[ "Мужчины", "Женщины" ]
)

Срдений возраст выживших/погибших

            Выжили    Погибли
Мужчины  27.382294  30.783120
Женщины  28.532468  25.666667

In [453]:
df["Fare"].agg(["min", "max", "mean"])

min       0.000000
max     512.329200
mean     32.096681
Name: Fare, dtype: float64

In [454]:
df["Age"].std()

np.float64(12.984932293690775)

In [455]:
most_payed_male = df.loc[(df["Age"] > 30) & (df["Pclass"] == 1)]
print(most_payed_male.shape[0])
most_payed_male.head(10)

123

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,C
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,C
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,S

In [456]:
some_surv_peop = df.loc[((df["Age"] < 18) | (df["Sex"] == "female")) & (df["Survived"] == 1)]
some_surv_peop.shape[0]

254

In [457]:
ticket_cost_3_cl = np.mean(df["Fare"].where(df["Pclass"] == 3))
df.loc[(df["Pclass"] == 3) & (df["Fare"] > ticket_cost_3_cl)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,S
...,...,...,...,...,...,...,...,...,...,...,...
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,C
860,861,0,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S

In [458]:
df.loc[(df["Age"] <= 40) & (df["Age"] >= 20) & (df["Embarked"] == "S")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S

In [459]:
group_by_sex_cls = df.groupby(["Pclass", "Sex"]).agg({
    "PassengerId" : "count",
    "Age" : "mean",
    "Survived" : "mean",
    "Fare" : "mean"
}).reset_index()
group_by_sex_cls

   Pclass     Sex  PassengerId        Age  Survived        Fare
0       1  female           92  33.630435  0.967391  106.693750
1       1    male          122  38.995246  0.368852   67.226127
2       2  female           76  28.703947  0.921053   21.970121
3       2    male          108  30.512315  0.157407   19.741782
4       3  female          144  23.572917  0.500000   16.118810
5       3    male          347  26.911873  0.135447   12.661633

In [460]:
ports_surv_stat = df.groupby(["Embarked"]).agg({
    "PassengerId" : "count",
    "Survived" : "mean"
})
ports_surv_stat

          PassengerId  Survived
Embarked
C                 168  0.553571
Q                  77  0.389610
S                 644  0.336957

In [461]:
df.groupby(["Pclass"]).agg({"Survived" : "mean"}).idxmax()["Survived"]

np.int64(1)

In [462]:
df.to_csv("titanic_processed.csv", index=False, sep=",")
group_by_sex_cls.to_csv("titanic_statistics.csv", index=False, sep=",")

In [463]:
pd.read_csv("titanic_processed.csv").head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S